### ISSUE TITLE
 Error: "undefined unsupported"

### ISSUE THREAD

**Issue by vlddm** [radarsu/rpc-websocket-client#3]
Test case:
[https://codesandbox.io/embed/awesome-chebyshev-wb2dy](https://codesandbox.io/embed/awesome-chebyshev-wb2dy)
Error visible in actual browser console, not a codesandbox one.

**Comment by radarsu** [comment]
My apologies. After adding isomorphic-ws and updating some dependencies I didn't do proper testing. I've added test suite and updated a lot of stuff in version `1.1.1`.

After just changing your version from codesandbox to 1.1.1 I received what's I believe a proper response:

<img width="1920" alt="2019-09-05 00_58_13-awesome-chebyshev-wb2dy - CodeSandbox" src="https://user-images.githubusercontent.com/7216948/64299131-50322700-cf78-11e9-9aa5-b4c5e8f4ff3a.png">
