### ISSUE TITLE
JSON-RPC response with null result raises error

### ISSUE THREAD

**Issue by otsuka** [radarsu/rpc-websocket-client#5]
When the websocket server returns a JSON-RPC successful response which has `null` result, rpc-websocket-client (version 1.1.3) throws TypeError as below:

#### Response JSON-RPC Message
```
{jsonrpc: "2.0", id: "29087a00-ebff-11e9-aefb-7b66852aac88", result: null}
```

#### Error 
```
home.js:341 Uncaught TypeError: Cannot read property 'code' of null
    at RpcWebSocketClient.push../node_modules/rpc-websocket-client/dist/rpc-websocket-client.es5.js.RpcWebSocketClient.isRpcError (home.js:341)
    at Object._this.idAwaiter.<computed> (home.js:186)
    at WebSocket.ws.onmessage (home.js:146)
```
(`home.js` is my Vue component script)

When a response message has a result value other than `null`, this error does not happen.

It seems that the response message is handled as a sucessful response, but this line is not properly processed.
https://github.com/radarsu/rpc-websocket-client/blob/master/src/rpc-websocket-client.ts#L176

**Comment by radarsu** [comment]
Added null (and other simple types) check to isRpcError function, so the problem should be fixed in 1.1.4.
