### ISSUE TITLE
How to close WebSocket connection 

### ISSUE THREAD

**Issue by otsuka** [radarsu/rpc-websocket-client#8]
RpcWebSocketClient class has `connect` method, but `disconnect` or `close` method is not defined.

Invoking `rpc.ws.close()` is preferred way?

**Comment by radarsu** [comment]
Yes, I try to not abstract the logic that doesn't need an abstraction. 

I'll add information about closing connection to README.md.

Let me know if you have any feature requests or another suggestions to improve the repository.

**Comment by otsuka** [comment]
Thank you for your response.
I understood the intent of your implementation.
